# Shortsub report, public bug tracking.
#
# Copyright (C) 2024  Dirk "YouDirk" Lehmann.  All rights reserved.

blank_issues_enabled: false
contact_links:
#  - name: Shortsub on Github.
#    url: https://github.com/Shortsub
#    about: Don't know what it's goal xD
#  - name: Shortsub forum
#    url: https://github.com/Shortsub/lalalala
#    about: Questions and answers here.
